export const SET_RECIPES = "SET_RECIPES";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_RECIPE_DETAIL = "SET_RECIPE_DETAIL";
export const TOGGLE_RECIPES_FETCHING_STATE = "TOGGLE_RECIPES_FETCHING_STATE";
export const TOGGLE_RECIPE_DETAIL_FETCHING_STATE =
  "TOGGLE_RECIPE_DETAIL_FETCHING_STATE";
export const SET_AUTOCOMPLETE_RECIPES = "SET_AUTOCOMPLETE_RECIPES";
