export const SET_RECIPES = "SET_RECIPES";
export const SET_SHOPPING_LIST_ITEM = "SET_SHOPPING_LIST_ITEM";
export const SET_GROCERY_ITEMS = "SET_GROCERY_ITEMS";
export const SET_USER = "SET_USER";
export const SET_MEALPLANS = "SET_MEALPLANS";
export const SET_MEALPLAN_TEMPLATE = "SET_MEALPLAN_TEMPLATE";
export const TOGGLE_USER_FETCHING_STATE = "TOGGLE_USER_FETCHING_STATE";
export const TOGGLE_GROCER_ITEMS_FETCHING_STATE =
  "TOGGLE_GROCER_ITEMS_FETCHING_STATE";
export const TOGGLE_MEALPLANS_FETCHING_STATE =
  "TOGGLE_MEALPLANS_FETCHING_STATE";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_RECIPE_DETAIL = "SET_RECIPE_DETAIL";
export const TOGGLE_RECIPES_FETCHING_STATE = "TOGGLE_RECIPES_FETCHING_STATE";
export const TOGGLE_RECIPE_DETAIL_FETCHING_STATE =
  "TOGGLE_RECIPE_DETAIL_FETCHING_STATE";
export const SET_AUTOCOMPLETE_RECIPES = "SET_AUTOCOMPLETE_RECIPES";
export const SET_AUTOCOMPLETE_GROCERY_ITEMS = "SET_AUTOCOMPLETE_GROCERY_ITEMS";
export const SET_SIMILAR= "SET_SIMILAR"
